### ISSUE TITLE
Web show UnimplementedError 

### ISSUE THREAD

**Issue by webaddicted** [hnvn/flutter_shimmer#42] opened 2021-01-13 17:20 UTC
@hnvn 
When I implement shimmer package app on **web app then it's show below error** but it's working om mobile side:

**======== Exception caught by scheduler library =====================================================
UnimplementedError
====================================================================================================**

**Comment by hnvn** [comment] 2021-01-14 07:17
Duplicate of #25

**Closed** 2021-01-14 14:44 UTC
