### ISSUE TITLE
Not supported for web.

### ISSUE THREAD

**Issue by sanalkv** [hnvn/flutter_shimmer#25] opened 2020-04-08 04:43 UTC
```
════════ Exception caught by scheduler library ═════════════════════════════════
UnimplementedError
═════════════════════════════════
```
I'm getting this error while running this package on flutter web.

**Comment by hnvn** [comment] 2020-04-18 08:58
I haven't ever touched Flutter web version. Welcome anyone who has experiences with it to contribute and bring this package on the web version.

**Comment by softmarshmallow** [comment] 2020-05-18 06:23
its been a while, we need official support for web.

**Comment by jagmit** [comment] 2020-06-16 15:58
I have never worked with low-level APIs such as `SingleChildRenderObjectWidget` or `RenderProxyBox` so I don't really know how I could help, but here is my error log regarding this issue:

<details><summary>Error log</summary>
<p>

```
example $ flutter run -d chrome
Running "flutter pub get" in example...                             1,8s
This application is not configured to build on the web.
To add web support to a project, run `flutter create .`.
Launching lib/main.dart on Chrome in debug mode...
Syncing files to device Chrome...                                       
24.886ms (!)                                       
Debug service listening on ws://127.0.0.1:50353/7F4MPD3AMFg=

Warning: Flutter's support for web development is not stable yet and hasn't
been thoroughly tested in production environments.
For more information see https://flutter.dev/web

🔥  To hot restart changes while running, press "r" or "R".
For a more detailed help message, press "h". To quit, press "q".
══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY
╞═════════════════════════════════════════════════════════
The following UnimplementedError was thrown during a scheduler callback:
UnimplementedError

When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 214:49  throw_
lib/_engine/engine/surface/scene_builder.dart 234:5
pushShaderMask
packages/flutter/src/rendering/layer.dart 1858:26                             addToScene
packages/flutter/src/rendering/layer.dart 445:5
[_addToSceneWithRetainedRendering]
packages/flutter/src/rendering/layer.dart 1068:14
addChildrenToScene
packages/flutter/src/rendering/layer.dart 2046:5                              addToScene
packages/flutter/src/rendering/layer.dart 445:5
[_addToSceneWithRetainedRendering]
packages/flutter/src/rendering/layer.dart 1068:14
addChildrenToScene
packages/flutter/src/rendering/layer.dart 1206:5                              addToScene
packages/flutter/src/rendering/layer.dart 445:5
[_addToSceneWithRetainedRendering]
packages/flutter/src/rendering/layer.dart 1068:14
addChildrenToScene
packages/flutter/src/rendering/layer.dart 1206:5                              addToScene
packages/flutter/src/rendering/layer.dart 445:5
[_addToSceneWithRetainedRendering]
packages/flutter/src/rendering/layer.dart 1068:14
addChildrenToScene
packages/flutter/src/rendering/layer.dart 1654:5                              addToScene
packages/flutter/src/rendering/layer.dart 805:5                               buildScene
packages/flutter/src/rendering/view.dart 232:36
compositeFrame
packages/flutter/src/rendering/binding.dart 408:18                            drawFrame
packages/flutter/src/widgets/binding.dart 867:13                              drawFrame
packages/flutter/src/rendering/binding.dart 286:5
[_handlePersistentFrameCallback]
packages/flutter/src/scheduler/binding.dart 1115:15
[_invokeFrameCallback]
packages/flutter/src/scheduler/binding.dart 1054:9
handleDrawFrame
packages/flutter/src/scheduler/binding.dart 970:5
[_handleDrawFrame]
lib/_engine/engine/window.dart 739:13                                         _invoke
lib/_engine/engine/window.dart 352:5
invokeOnDrawFrame
lib/_engine/engine.dart 214:18                                                <fn>
══════════════════════════════════════════════════════════════════════════════════════════
══════════
Another exception was thrown: UnimplementedError
Another exception was thrown: UnimplementedError
```

</p>
</details>

Maybe this has something to do with [ShaderMask not being available in web?](https://github.com/flutter/flutter/issues/44152)

@hnvn is there a way to implement this effect while avoiding the use of `ShaderMask`/`ShaderMaskLayer`?

**Comment by hnvn** [comment] 2020-06-17 02:21
It depends heavily on rendering API (i.e. canvas and blend mode). I have tried to work on this issue but have not found a solution yet. It seems we may as well wait for Flutter engine support these APIs on Web

**Comment by amitkot** [comment] 2020-07-06 06:51
(Thanks for the package, I love it on mobile!)
Re web support, in the meantime it might be better to remove the "web" tag from this package on pub.dev.

**Comment by nemoryoliver** [comment] 2020-08-14 12:28
Web support would be great!! waiting....

**Comment by hnvn** [comment] 2020-08-15 03:49
It depends on this [issue](https://github.com/flutter/flutter/issues/44152)

**Comment by diamond-shine** [comment] 2020-08-15 19:27
@hnvn Please remove "web" tag.
The above issue brought me here.
![image](https://user-images.githubusercontent.com/49306532/90320034-3817a580-df46-11ea-87bf-9803a97c63f1.png)

**Comment by DRSchlaubi** [comment] 2020-10-04 19:08
> @hnvn Please remove "web" tag.
> The above issue brought me here.
> I hope we can use shimmer in Flutter web too. :)
> ![image](https://user-images.githubusercontent.com/49306532/90320034-3817a580-df46-11ea-87bf-9803a97c63f1.png)

The WEB badge is not added by the authors it is added by the pub.dev analyzer seeing that this is a package (not a plugin) and then adding it

**Comment by lbarqueira** [comment] 2020-10-11 18:51
Important that WEB badge not be included. Does not work for web

════════ Exception caught by scheduler library ═════════════════════════════════
UnimplementedError
════════════════════════════════════════════════════════════════════════════════

**Comment by creativecreatorormaybenot** [comment] 2020-10-29 21:42
I assume that the canvas operations that are unsupported on web with DomCanvas (HTML rendering) **do work** with **CanvasKit**.  
If you want to give that a try, you can run your Flutter web app using the following command:

```
flutter run -d chrome --dart-define=FLUTTER_WEB_USE_SKIA=true
```

More information on that [can be found here](https://twitter.com/creativemaybeno/status/1321623116716658688?s=20).  
Note that I did not look into this further - I was made aware of this issue and thought that I might be able to offer help. In case anyone tries this out, let me know if it worked :)

**Comment by mzdm** [comment] 2020-10-30 00:42
> I assume that the canvas operations that are unsupported on web with DomCanvas (HTML rendering) **do work** with **CanvasKit**.
> If you want to give that a try, you can run your Flutter web app using the following command:
> 
> ```
> flutter run -d chrome --dart-define=FLUTTER_WEB_USE_SKIA=true
> ```
> 
> More information on that [can be found here](https://twitter.com/creativemaybeno/status/1321623116716658688?s=20).
> Note that I did not look into this further - I was made aware of this issue and thought that I might be able to offer help. In case anyone tries this out, let me know if it worked :)

Unfortunately even with that flag it doesn't work.
`Another exception was thrown: UnimplementedError`

Hopefully flutter/engine#21756 makes it possible

**Comment by talhabalaj** [comment] 2020-12-19 15:01
@flutter/flutter#44152

**Comment by sanalkv** [comment] 2020-12-20 08:01
can we implement a workaround using javascript package ?

**Comment by talhabalaj** [comment] 2020-12-20 11:57
> can we implement a workaround using javascript package ?

Maybe. While the `ShaderMask` is baked for Flutter Web. You can use some other shimmer package that doesn't depend on ShaderMask. This one is the best one tho.

**Comment by mzdm** [comment] 2021-02-12 22:15
Seems like that it will be soon possible! https://github.com/flutter/engine/pull/24029

**Comment by mzdm** [comment] 2021-02-22 19:48
https://github.com/flutter/flutter/pull/76536 got merged and can confirm that on `master channel` the package is working on web now! (both HTML and Skia)
```
Flutter 1.27.0-5.0.pre.99 • channel master •
https://github.com/flutter/flutter.git
Framework • revision 9b6d267ea3 (85 minutes ago) • 2021-02-22 21:21:03 +0300
Engine • revision 07afcf7d0f
Tools • Dart 2.13.0 (build 2.13.0-52.0.dev)
```
![shimmer](https://user-images.githubusercontent.com/67197047/108761489-36f7ae80-754f-11eb-8b8e-a156db9f883f.gif)

big thanks for @ferhatb

**Comment by roman-122** [comment] 2021-02-22 19:51
Great work! Awesome.

**Comment by XSiyabonga** [comment] 2021-02-27 08:02
> amework • revision 9b6d267ea3 (85 minutes ago) • 2021-02-

I switched to the master channel...

Flutter 1.27.0-9.0.pre.110 • channel master •
https://github.com/flutter/flutter.git
Framework • revision 666c950989 (15 hours ago) • 2021-02-26 08:46:00 -0800
Engine • revision 1515b1d4a4
Tools • Dart 2.13.0 (build 2.13.0-79.0.dev)

im also on veriosn 1.1.2

and it didn't work. Am I missing something

**Comment by mzdm** [comment] 2021-02-27 09:47
try to run with `flutter run -d chrome --web-renderer=html`

**Comment by XSiyabonga** [comment] 2021-02-27 11:35
Tried it and it worked thanks but it still has issues. Mine currently being it renders only when the view is small for some strange reason. Almost as if the renderer is only running from the left of the tab on a small section.

**Comment by mzdm** [comment] 2021-02-27 11:40
Do you have a small code sample? I could try.
I think it is better to wrap with Shimmer only small parts of widgets not whole pages or so that may cause issues as well (and is performance heavy).

You can also post an issue to https://github.com/flutter/flutter/issues

**Comment by ferhatb** [comment] 2021-03-02 00:54
@XSiyabonga please file an issue with a small sample, we'll take a look. We haven't closed this issue since we are still wrapping up some work around this. Want to make sure we cover your case as well.

**Comment by britannio** [comment] 2021-03-30 14:44
Does this work with the canvaskit renderer on the stable channel? I'm getting the following `UnimplementedError`:
`flutter lib/_engine/engine/canvaskit/layer scene builder.dart 196:5 push ShaderMask`

**Comment by mzdm** [comment] 2021-03-30 14:56
> Does this work with the canvaskit renderer on the stable channel? I'm getting the following error:
> 
> ```
> ======== Exception caught by scheduler library =====================================================
> The following UnimplementedError was thrown during a scheduler callback:
> UnimplementedError
> 
> When the exception was thrown, this was the stack: 
> dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 236:49  throw_
> lib/_engine/engine/canvaskit/layer_scene_builder.dart 196:5                   pushShaderMask
> packages/flutter/src/rendering/layer.dart 1779:26                             addToScene
> packages/flutter/src/rendering/layer.dart 407:5                               [_addToSceneWithRetainedRendering]
> packages/flutter/src/rendering/layer.dart 994:14                              addChildrenToScene
> ```

ShaderMask was not implemented inside the Flutter framework on the web platform, so that's why it throws an error. It was recently added but it didn't land to a stable channel yet. When I tried beta channel last time it still had some issues (but didn't throw an error). So you need to switch to dev/master channel if you want to use this on the web..

**Comment by britannio** [comment] 2021-03-30 15:35
That's a shame, seems like support was added 11 days before Flutter 2.0 was released (https://github.com/flutter/flutter/pull/76536). I doubt it's eligible for a hotfix considering that it's still partially broken https://github.com/flutter/flutter/issues/77051 and it's not a regression or critical fix https://github.com/flutter/flutter/wiki/Flutter-Cherrypick-Process

**Comment by cirnok** [comment] 2021-04-02 14:21
I have the same problem and managed to fix it by downgrading to version 1.0.1.
Flutter: stable, 2.0.3. Use SKIA render.

**Comment by hnvn** [comment] 2021-06-21 04:08
I confirm that shimmer works on Web with Flutter v2.2.2. Anybody can confirm it as well?

**Comment by XSiyabonga** [comment] 2021-06-21 06:48
Cant seem to find a branch or the v2.2.2 version, is it published? The latest version is still v2.0.0

**Comment by creativecreatorormaybenot** [comment] 2021-06-21 07:21
@XSiyabonga they are not referring to the package version but the **Flutter version** (`flutter --version` → `flutter upgrade`).

**Comment by XSiyabonga** [comment] 2021-06-21 07:23
> @XSiyabonga they are not referring to the package version but the **Flutter version** (`flutter --version` → `flutter upgrade`).

Oh my bad thanks. Will test it out thanks

**Comment by XSiyabonga** [comment] 2021-06-21 09:04
> I confirm that shimmer works on Web with Flutter v2.2.2. Anybody can confirm it as well?

I can confirm too that its working with Flutter v2.2.2

**Comment by hnvn** [comment] 2021-06-28 02:05
I'm going to close this issue. Thanks you guys

**Closed by hnvn** 2021-06-28 02:05 UTC
Labels: enhancement
