### ISSUE TITLE
UnimplementedError. On web

### ISSUE THREAD

**Issue by MCode-Team** [hnvn/flutter_shimmer#46] opened 2021-04-16 16:31 UTC
Another exception was thrown: UnimplementedError .  On web

**Comment by abdulmominsakib** [comment] 2021-04-19 01:06
Facing the same error..

**Comment by ricpar11** [comment] 2021-05-06 16:01
Me too, this still happens

**Comment by mitesh77** [comment] 2021-05-19 18:37
not working on the web. I also facing this issue too.

**Comment by hnvn** [comment] 2021-06-21 04:08
Duplicate of #25

**Closed by hnvn** 2021-06-21 04:08 UTC
