### ISSUE TITLE
Web not working in any way

### ISSUE THREAD

**Issue by Niggelgame** [hnvn/flutter_shimmer#34] opened 2020-08-28 18:57 UTC
```dart
════════ Exception caught by scheduler library ═════════════════════════════════════════════════════
UnimplementedError
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by scheduler library ═════════════════════════════════════════════════════
UnimplementedError
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by scheduler library ═════════════════════════════════════════════════════
UnimplementedError
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by scheduler library ═════════════════════════════════════════════════════
UnimplementedError
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by scheduler library ═════════════════════════════════════════════════════
The following UnimplementedError was thrown during a scheduler callback:
UnimplementedError

When the exception was thrown, this was the stack: 
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 212:49  throw_
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/html/scene_builder.dart 231:5              pushShaderMask
packages/flutter/src/rendering/layer.dart 1825:26                                                                          addToScene
packages/flutter/src/rendering/layer.dart 444:5                                                                            [_addToSceneWithRetainedRendering]
packages/flutter/src/rendering/layer.dart 1035:14                                                                          addChildrenToScene
...
════════════════════════════════════════════════════════════════════════════════════════════════════
```

I keep receiving this Error while trying to use the Shimmer Package for Web.

Example Code for a not working widget: 

```dart
class LoadingSubMenuButton extends StatelessWidget {
  final double width;
  final double horizontalMargin;

  const LoadingSubMenuButton({
    Key key,
    this.width,
    this.horizontalMargin = 5,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return CustomContainer(
      height: 35,
      margin: EdgeInsets.symmetric(horizontal: this.horizontalMargin),
      padding: const EdgeInsets.symmetric(horizontal: 7),
      width: width,
      child: Row(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          ShimmerBox(height: 20, width: 90,),
        ],
      ),
    );
  }
}

class ShimmerBox extends StatelessWidget {
  final double height;
  final double width;

  const ShimmerBox({Key key, @required this.height, @required this.width,}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Shimmer.fromColors(
      baseColor: Colors.grey,
      highlightColor: Colors.grey[200],
      child: Container(
        height: height,
        width: width,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(5),
          color: Colors.black,
        ),
      ),
    );
  }
}
```

This is my `flutter doctor -v` output:

```dart
[√] Flutter (Channel dev, 1.22.0-1.0.pre, on Microsoft Windows [Version 10.0.19041.450], locale de-DE)
    • Flutter version 1.22.0-1.0.pre at C:\Users\Besitzer\fvm\versions\dev
    • Framework revision ce40de69b7 (8 days ago), 2020-08-20 07:31:50 -0700
    • Engine revision 81027ab0cc
    • Dart version 2.10.0 (build 2.10.0-45.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\Besitzer\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_SDK_ROOT = C:\Users\Besitzer\AppData\Local\Android\Sdk
    • Java binary at: C:\Users\Besitzer\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 40.1.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[!] Android Studio (version 4.0)
    • Android Studio at C:\Users\Besitzer\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (4 available)
    • Pixel 3a (mobile) • 98GAY14VV1 • android-arm64  • Android 11 (API 30)
    • Web Server (web)  • web-server • web-javascript • Flutter Tools
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 84.0.4147.135
    • Edge (web)        • edge       • web-javascript • Microsoft Edge 84.0.522.63

! Doctor found issues in 1 category.
```

 I would love to receive information, if I am doing something completely wrong, or if this is an actual issue with the plugin.

**Comment by hnvn** [comment] 2020-08-28 23:53
Duplicate of #25

**Closed** 2020-08-28 23:53 UTC
